version: '2'
services:
  nym-mixnode:
    image: nym-mixnode
    container_name: nym-mixnode
    restart: unless-stopped
    ports:
      - 1789:1789
    build:
      context: ./
      args:
        - NYM_VERSION=v0.9.2
    volumes:
      - ./data:/root/.nym/mixnodes/mixer/data
      - ./config.toml:/root/.nym/mixnodes/mixer/config/config.toml
